---
- name: "Restart graylog-server"
  ansible.builtin.service:
    name: "graylog-server"
    state: "restarted"
    daemon_reload: true
    enabled: true

- name: "Update apt"
  ansible.builtin.apt:
    update_cache: true
